version: "3.8"
services:
  postgres:
    container_name: cgwire-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
  redis:
    container_name: cgwire-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
